### ISSUE TITLE
Windows executable is not the latest version

### ISSUE THREAD

**Issue by aniforprez** [boppreh/steamgrid#101]
The Windows executable is missing a lot of the options that seem to have been added later through PRs and such. The release versions linked in the README seems to be far behind the code. I manually built the executables and got it working but seems to me that we need to update the release executables

**Comment by cheatfreak47** [comment]
Here is a build up to date with [20c3e37](https://github.com/boppreh/steamgrid/commit/20c3e37c1f6e0751de648dafb1c111afc2952303) for any onlookers. 
[steamgrid-newbuild.zip](https://github.com/boppreh/steamgrid/files/7917296/steamgrid-newbuild.zip)

**Comment by boppreh** [comment]
Version v3.3.0 released just now with all the fixes and features so far.
