### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by aniforprez** [boppreh/steamgrid#102]
Building on Go versions 1.17 and up is not working because the project has undocumented external dependencies with no `go.mod` or `go.sum` file. All that needs to be done is run `go mod init <package name>` and then add the three or so dependencies the project needs using `go get <dependency>` and run `go mod tidy` which should allow building the module on the new go version

**Comment by cheatfreak47** [comment]
@aniforprez could you share a build? I have no familiarity with Go programming language stuff, and I just want the latest release.
It's ridiculous the dev hasn't updated the releases in over a year >:V

**Comment by cheatfreak47** [comment]
Nevermind, I was able to sort it out. Here is a build up to date with 20c3e37.
[steamgrid-newbuild.zip](https://github.com/boppreh/steamgrid/files/7917296/steamgrid-newbuild.zip)

**Comment by boppreh** [comment]
Thanks a lot for the help @aniforprez , your instructions helped me build it again with the new features and bugfixes. Please check release v3.3.0.
