### ISSUE TITLE
Incompatible with new changes to ui

### ISSUE THREAD

**Issue by ruscur** [boppreh/steamgrid#11]
`src/github.com/boppreh/go-ui/ui.go:8: not enough arguments in call to ui.NewWindow
src/github.com/boppreh/go-ui/ui.go:13: undefined: ui.Layout
src/github.com/boppreh/go-ui/ui.go:14: w.SetSpaced undefined (type ui.Window has no field or method SetSpaced)
src/github.com/boppreh/go-ui/ui.go:15: w.Open undefined (type ui.Window has no field or method Open)
src/github.com/boppreh/go-ui/ui.go:16: w.Center undefined (type ui.Window has no field or method Center)
src/github.com/boppreh/go-ui/ui.go:30: progressBar.SetProgress undefined (type ui.ProgressBar has no field or method SetProgress)
src/github.com/boppreh/go-ui/ui.go:31: w.Closing undefined (type ui.Window has no field or method Closing)
src/github.com/boppreh/go-ui/ui.go:33: cancelButton.Clicked undefined (type ui.Button has no field or method Clicked)
src/github.com/boppreh/go-ui/ui.go:44: undefined: ui.MsgBoxError
src/github.com/boppreh/go-ui/ui.go:44: too many errors`

Looks like some lib changes in ui, should be pretty easy to fix

**Comment by boppreh** [comment]
Unfortunately that library has been very unstable the past months. The author is constantly rewriting things, and features tend to be lost during those rewrites. I have contributed to it and find it one of the best things to have happened to Go, but it's just too rapidly changing to keep up with right now.

For example, last I checked the `MsgBoxError` class had been removed with no alternatives. `Layout` disappeared too, but that's easier to replace.

I'll wait for the next backend rewrite mentioned in the [February update](https://github.com/andlabs/ui#updates), but I'll happily accept pull requests.

**Comment by ruscur** [comment]
Might send a PR depending on free time - have you seen https://github.com/google/gxui ? Might be a suitable replacement that is better supported

**Comment by boppreh** [comment]
All code in this package is experimental and will have frequent breaking changes.
    The code is currently undocumented, and is certainly not idiomatic Go.
    It will be heavily refactored over the coming months.

Hmm. Still, it's a shot. I'll try migrating and decide which one to keep.

Thank you.
