### ISSUE TITLE
White logo problems

### ISSUE THREAD

**Issue by Jpxe** [boppreh/steamgrid#113]
Hello, thanks for a great application. I'm trying to download white logo covers from steamgriddb but I can't seem to get it right. I would like all my games to have white logo covers (when it exists). What happens is that steamgrid either skips all with covers on steam or it downloads mostly regular covers from IGDB. I would like to either:
1. Download white logo from steamgriddb, if that doesn't exist then download alternate from steamgriddb, if that doesn't exist then the steam server, and last igdb
2. Download white label from steamgriddb, if that doesn't exist do nothing

Here's my current command: 
`steamgrid --steamgriddb 0000 --igdbclient 0000 --igdbsecret 0000 --styles white_logo --nsfw any --skipsteam --skipgoogle` - this will download some white_logo covers but miss a lot also it mostly downloads from IGDB

I've tried without `--skipsteam` but then it won't download any white logo covers for games that have covers on the steam server. I've also tried with `--styles "white_logo,alternate"` but it seems it misses a lot of white logo then and mostly downloads alternate.

Is there a way to download all white logo covers that exists for my library?

**Comment by Lucki** [comment]
Run multiple times, the adjacent runs won't overwrite already found images.

**Comment by Jpxe** [comment]
@Lucki that will download covers from IGDB that don't have white logos

**Comment by Jpxe** [comment]
If nothing else I would like to skip IGDB

**Comment by Jpxe** [comment]
It will still download from IGDB
