### ISSUE TITLE
COMPILE THE APP EXE PLS 

### ISSUE THREAD

**Issue by SteavenGamerYT** [boppreh/steamgrid#115]
COMPLIE IT or https://github.com/SteavenGamerYT/steamgrid get my exe i complied it for you pls pls get it or just use
go mod init
go mod init example.com/m/v2
go mod tidy
go build -o steamgrid.exe

this what i used and it complied fine and it works i tried it unless you update the exe i will keep updating it

**Comment by nithou** [comment]
Tried to include latest changes on my side and compile but only have Mac's and Steamdeck, when I try to compile for Windows using GOARCH it gives error, any idea how it's doable?
