### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by qwerty-space** [boppreh/steamgrid#14]
The one thing I don't like about this is the overlays.  Don't get me wrong, they look good, they're just not for me.  It would be cool if you could add some alternatives, like a far less obvious one.  Also it would be good if you could add completely transparent versions, so that we can remove certain overlays we don't want.

This is a great tool, Thanks!

**Comment by boppreh** [comment]
Thanks for the feedback qwery-space. The guys over [/r/steamgrid](https://www.reddit.com/r/steamgrid) (not related to this program) have made awesome overlays for Steam. More specifically, here's a filter that shows only the overlays they have: https://www.reddit.com/r/steamgrid/search?q=[o]&restrict_sr=on&sort=relevance&t=all

You can download any of them, pop inside the `overlays by category` folder with the name of the category you want to overlay, and it should be applied on the next run of the program.

Does this help?

**Comment by qwerty-space** [comment]
Not entirely.  I was thinking of providing a way to remove the overlays.  That's what I mean by "they're not for me". I don't like to have overlays on the steamgrid.

**Comment by boppreh** [comment]
Oh, okay. Just like you can add new overlays by naming them with your categories, you can just delete the overlay images (or the entire `overlays by category` folder) and they will not be applied.

**Comment by qwerty-space** [comment]
That's fine.  However, if you apply an overlay you don't like, you have to use a transparent image to remove it.

Date: Wed, 4 Nov 2015 08:49:03 -0800

**Comment by boppreh** [comment]
If that's so, it's a bug. The process goes like this:

    for every game for every user
        restore backup image, if there's one
        if there's no image, download one
        save a backup
        apply overlay

Notice if you run it without an overlay, it'll first restore a non-overlaid backup, and try applying a new overlay (if there's one). This is done to avoid stacking overlays across runs and correctly clearing overlays between runs.

Did you try it and it didn't work, or did you assume it wouldn't work?

**Comment by qwerty-space** [comment]
I might be remembering incorrectly.  This was a while ago.  All I know is that to remove the overlay I created a transparent version.I probably didn't need to though.
Date: Thu, 5 Nov 2015 05:21:38 -0800

**Comment by boppreh** [comment]
Okay then. If you don't mind, I'll close the issue for now. Thanks for the feedback.
