### ISSUE TITLE
different image for recently/now played game (header.jpg)

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [boppreh/steamgrid#146]
Steam grid library image for recently played (or now played) game is different than the normal 600x900 image:

_Normal (600x900) image:_
![Screenshot_20230410_004802](https://user-images.githubusercontent.com/29522138/230800006-12d36a40-b1c2-4a58-8bc7-ee90e320873d.png)

_Recently played (now played) image:_
![Screenshot_20230410_004908](https://user-images.githubusercontent.com/29522138/230800031-f1f931cf-66c0-4a18-87b1-54245ea7458f.png)

Is there a support for customizing differently those two?

btw, you could get normal 600x900 image from
`cdn.cloudflare.steamstatic.com/steam/apps/<appid>/library_600x900.jpg`
and the second one is
`cdn.cloudflare.steamstatic.com/steam/apps/<appid>/header.jpg`

Original images for the game on my screenshots (appid 774171):

<details>
<summary><a href=https://cdn.cloudflare.steamstatic.com/steam/apps/774171/library_600x900.jpg>library_600x900.jpg</a></summary>
<img src=https://cdn.cloudflare.steamstatic.com/steam/apps/774171/library_600x900.jpg title=library_600x900.jpg />
</details>

<details>
<summary><a href=https://cdn.cloudflare.steamstatic.com/steam/apps/774171/header.jpg>header.jpg</a></summary>
<img src=https://cdn.cloudflare.steamstatic.com/steam/apps/774171/header.jpg title=header.jpg />
</details>

**Comment by nondetect** [comment]
it's already existing in this program, first your image by default named - cover, and second is banner.

**Comment by papaj-na-wrotkach** [comment]
I am closing this issue as I found out that steamgrid uses the same image for header and banner - #148
