### ISSUE TITLE
Logo, banner, cover art not found for all games

### ISSUE THREAD

**Issue by Danzikks** [boppreh/steamgrid#151]
Hello!
![image](https://github.com/boppreh/steamgrid/assets/149537573/7beee370-5cba-4a3b-a9a7-dbca902de932)
![image](https://github.com/boppreh/steamgrid/assets/149537573/a48c4cc5-fcdc-496d-b6be-8c1d8165f4c4)

I was trying to figure out what to do. I deleted the userdata folder. 
I deleted the Steam download cache. Can you please tell me what to do?

**Comment by TrungMC** [comment]
I reread the code and the author actually used akamai sources, so possibly the game id and the app id not not correct.
