### ISSUE TITLE
Steamgrid not working in Linux Mint Debian Edition 2

### ISSUE THREAD

**Issue by Gameranand** [boppreh/steamgrid#16]
I am trying to run it in mint LMDE2 but it gives me error and each time it gives me error it actually copies a single image in the directory but refuses to go further than 1 game. I am attaching a screenshot of the error and no matter which first game it searches it refuses to go further with the same error.
![screenshot from 2016-01-29 20 16 24](https://cloud.githubusercontent.com/assets/11816991/12678663/ebc05346-c6c5-11e5-8280-dc0d2a8157de.png)

**Comment by boppreh** [comment]
Hi

Thanks for the report. The problem is already known (see Issue #15 ). 

GermainZ suggested this:

> An easy workaround is to create a symbolic link to the Steam directory (such that its path contains no dots), then passing that as an argument to steamgrid.

So it's just `ln -s ~/.local/share/Steam ~/dotlesssteam; ~/Downloads/steamgrid /home/gameranand/dotlesssteam`
