### ISSUE TITLE
Can't Launch Program in Linux

### ISSUE THREAD

**Issue by Gameranand** [boppreh/steamgrid#17]
Hi,
I am using Linux Mint LMDE2 64 bit OS. I downloaded steamgrid and extracted it but can't launch the program. Nothing happens when I double click steamgrid icon. It was working fine on my Linux Mint LMDE2 32 bit but its not working in 64 bit at all. I even tried to launch it in root mode but still can't launch it.
Please tell me if I have to do something else as well to run it. I am very used to it and its hard to live without this program. I use it on my primary gaming PC as well.

Thanks.

**Comment by boppreh** [comment]
Hi Gameranand

Try running it from the terminal. Errors are usually displayed on the screen, but it's possible the program broke before starting the UI. By running it inside a terminal it should print the error.

**Comment by Gameranand** [comment]
This is the error that I got

![image](https://cloud.githubusercontent.com/assets/11816991/12923281/23743146-cf7b-11e5-9604-1b47ee8db886.png)

I also tried running apt-get upgrade after apt-get update but didn't got any luck with this issue.

**Comment by boppreh** [comment]
Make sure you have `libgtk3` installed:

    sudo apt-get install libgtk-3-0

**Comment by Gameranand** [comment]
Yup I have it installed. Same problem still.

**Comment by MrMeatboy** [comment]
Same problem on Ubuntu 14.04

**Comment by boppreh** [comment]
Hi MrMeatboy. Sorry for the problem, I still don't know what could be. I'm working on a partial rewrite to address the GUI problems, hopefully this is also the cause of this startup problem.

**Comment by boppreh** [comment]
GUI has been removed. Steamgrid now has zero dependencies.

Please comment if the issue persists.

**Comment by Gameranand** [comment]
Its working now. Thanks a ton.

![image](https://cloud.githubusercontent.com/assets/11816991/13598983/d528fcb0-e546-11e5-91a4-8b59212f5cac.png)

**Comment by boppreh** [comment]
Great to hear it. Thank you for your patience.
