### ISSUE TITLE
Allow silent launch?

### ISSUE THREAD

**Issue by XenonPK** [boppreh/steamgrid#18]
Is it possible to launch the program with no gui to update everything in an automated way? Once per day/hour/week for instance?
If not, It may be a feature worth considering

**Comment by boppreh** [comment]
Working on it.

**Comment by boppreh** [comment]
GUI code has been removed. Technically, every launch is now silent. There is a "press enter to close" at the end, but you can skip that by feeding it a line at stdin.

As for automatic runs, this is not on the table right now. You can use crontab on Linux, or Window's equivalent, but built-in support is out of scope at the moment.

Please drop me a line if this doesn't solve your problem.
