### ISSUE TITLE
The played overlay is identical to the played one

### ISSUE THREAD

**Issue by xrogaan** [boppreh/steamgrid#23]
Having two identical overlay can be a bit disturbing for the user. A change of colors could do the trick though.

Changed mine to this:
![played](https://cloud.githubusercontent.com/assets/74860/13616046/7a1ba890-e578-11e5-9f7b-12d04d4a4909.png)

**Comment by boppreh** [comment]
Good idea. I put those overlays as examples, but this definitely makes the experience smoother.

I've updated release v1.30 to use the image you suggested. Thank you.

**Comment by xrogaan** [comment]
On a side note, would it be possible to get access to your base blueprint for the overlay if you have any? I'm not so much of a graphical designer, but others could use it to create their own images while keeping the consistency between overlays.

**Comment by boppreh** [comment]
They are not mine. You can find more overlays at [/r/steamgrid](https://www.reddit.com/r/steamgrid/) (related, but not about this program). They have a wiki page with a list of overlays: https://www.reddit.com/r/steamgrid/wiki/overlays

Hope this helps.
