### ISSUE TITLE
Is it possible to implement the option to automatically close when finished?

### ISSUE THREAD

**Issue by Daxiongmao87** [boppreh/steamgrid#24]
I have this running as a scheduled task and would like it as hands-off as possible

**Comment by boppreh** [comment]
There's no builtin option in the program, but you can use your OS.

Windows:

    @echo | steamgrid.exe

Linux:

    echo | steamgrid

This will still print the "press enter to close" message, but it'll go away by itself. Tell me if it works for you.

**Comment by Daxiongmao87** [comment]
thanks!

**Comment by boppreh** [comment]
I'll assume it worked and close the issue. If you still experience any problems, feel free to reopen.

**Comment by boppreh** [comment]
By the way, _not_ running the tool automatically just saved my library. Steam accidentally deleted all my categories and "synchronized" to other machines, but I was able to recover by looking at the (now outdated) overlays.
