### ISSUE TITLE
Images downloaded instead of using local (preferred) files

### ISSUE THREAD

**Issue by andrewjmetzger** [boppreh/steamgrid#29]
Running SteamGrid on Windows 10, with the latest release, the application downloads images from the internet instead of using local ones unless the banner is manually set beforehand. Overlays work as expected.

Directory structure as follows:
- Images are in `~/Pictures/steamGrid/blurred/<name-of-game>.png`
  - For example, the Portal 2 banner would be `../blurred/Portal 2.png`
  - App is located in `~/Pictures/steamGrid/steamgrid-windows/`

I have tried placing images in the same directory as the application, but this has no effect. Any assistance would be appreciated.

**Comment by boppreh** [comment]
This is more of a feature request, and has been implemented in the [v2.0.0](https://github.com/boppreh/steamgrid/releases/tag/v2.0.0). Feedback welcome.
