### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cdrage** [boppreh/steamgrid#30]
Hiya!

Had to git clone and build manually in order to fix the whole "grabbing new images issue".

Mind doing a new release for users whom don't want to install/compile Go on Windows platforms?

**Comment by boppreh** [comment]
Hi

I'll be doing that, but it'll take a few more days. I've been stupidly busy, and unfortunately my open source projects took a hit in activity.

Thank you very much for your interest, and sorry for the lack of responses.

**Comment by boppreh** [comment]
Sorry. It took more than a few days.

https://github.com/boppreh/steamgrid/releases/tag/v1.4.0
