### ISSUE TITLE
Grid images are low quality.

### ISSUE THREAD

**Issue by Qwerty-Space** [boppreh/steamgrid#31]
The images steamgrid downloads seem to be very low quality, with JPEG artifacts.

You could get around this by not allowing it to download JPEG/JPG images, or incorporating [waifu2x](https://github.com/lltcggie/waifu2x-caffe) to denoise the images, it does an excellent job.  For example: http://i.imgur.com/vCjX7nD.png

**Comment by Qwerty-Space** [comment]
Okay, after looking at the files and comparing the original to the applied version, it seems that when steamgrid applies an overlay, or copies the file it lowers the quality.

As seen here:
http://i.imgur.com/20SPXDn.png

**Comment by boppreh** [comment]
You're right, I didn't think of jpgs and quality loss of reencodings. I think waifu2x would be overkill (and a huge dependency), and artificially banning an image format because it might not look as good is too harsh. Maybe changing the code to reduce as much as possible reencodings and emittings warnings...

I'll have to think about it. Thanks for reporting this issue.

**Comment by boppreh** [comment]
Steamgrid is now more careful when reencoding, and never reencodes an image more than once. Also, if the original was lossless (png), the overlaid version is also encoded as png. This should fix some of the quality issues. Thanks for the feedback.

I still hold that Waifu2x is overkill, and may even ruin the aesthetic of some images (e.g. pixelated banners).

**Comment by Qwerty-Space** [comment]
Yeah, maybe it is overkill. But waifu2x can just be used to genocide without upscaling.
If they're too low quality I can just use it on the whole folder anyway.

Thursday, 18 May 2017, 02:10a.m. +01:00 from BoppreH notifications@github.com<mailto:notifications@github.com>:


Steamgrid is now more careful when reencoding, and never reencodes an image more than once. Also, if the original was lossless (png), the overlaid version is also encoded as png. This should fix some of the quality issues. Thanks for the feedback.

I still hold that Waifu2x is overkill, and may even ruin the aesthetic of some images (e.g. pixelated banners).
