### ISSUE TITLE
Grid images being corrupted

### ISSUE THREAD

**Issue by rip3535** [boppreh/steamgrid#32]
Non steam game grid images are downloading but they're all 295KB and will not display in windows.

Edit: after reviewing the files in C:\Program Files (x86)\Steam\userdata\config\grid it appears the non steam games are downloading .html files of the steam home page and renaming them as .jpg.

**Comment by boppreh** [comment]
This smells like Steam changed their URLs. Checking now.

**Comment by boppreh** [comment]
Yep, the Steam CDN changed URL and was redirecting to the home page. I've updated the URL in the source code. https://github.com/boppreh/steamgrid/commit/db289021a3b94b2e6565b6f1e5376ac78d8c26ab should fix this issue.

Thank you for the report.
