### ISSUE TITLE
Image files contain html instead of image data

### ISSUE THREAD

**Issue by thundercatsNZ** [boppreh/steamgrid#38]
Hi, thanks for making this - exactly what I needed for my Steam Machine as 75% of my library are emulated titles and non-Steam games.

I downloaded the program and it runs ok, saying it finds images for all of my non-Steam games. But I went into Grid View/Big Picture and no new images showed up. I looked at the files inside /config/grid and the images were created, but all have an identical file size (~270kb). I opened one up in a text editor and its actually a page of html... looks like the Steam homepage.

Took a quick look at the source and my browser can resolve the akamai CDN url just fine if I copy an appID into it.

Any ideas how to resolve this?

Thanks!

**Comment by boppreh** [comment]
Hi

This is a known big that was supposed to be fixed on the latest release. Can you check if you are running the latest version? Thanks.

**Comment by boppreh** [comment]
By latest release I mean v1.4.0 released four days ago: https://github.com/boppreh/steamgrid/releases/tag/v1.4.0

**Comment by thundercatsNZ** [comment]
Great, the latest release works perfectly!

Thanks for your quick response 👍

**Comment by boppreh** [comment]
Great to hear that!
