### ISSUE TITLE
Overlays not found when overriding Steam location

### ISSUE THREAD

**Issue by henry-95** [boppreh/steamgrid#4]
I have Steam installed on a separate hard drive so it doesn't find its location, so I drag it onto steamgrid.exe and it works, but it doesn't find the overlays.

The overlays are detected when I run steamgrid on its own, but not when overriding the Steam location.

**Comment by SXRWahrheit** [comment]
Program doesn't open with nonstandard Steam install directory. Tries to find it in C:\.

**Comment by boppreh** [comment]
Hi SXRWahrheit

As far as I know there's no way to find Steam if it has been installed in a non-standard location. But you can still drag and drop the Steam installation folder over `steamgrid.exe` for a manual override.

If the problem persists, or you know of a way of deriving Steam's real installation path, please open another issue.
