### ISSUE TITLE
Use ConsoleGrid.com for Emulator Games Pictures

### ISSUE THREAD

**Issue by malger** [boppreh/steamgrid#43]
Checkout 
http://consolegrid.com/

they offer a lot of steam banners for emulated games, also they have a rating system so the results maybe promising.

Anyway thanks for the great little script, saves a lot of time^^

**Comment by boppreh** [comment]
Hi @malger !

We had this discussion before. My position is that as long as those images are indexed by Google Image Search, Steamgrid will find them automatically. I think this is a better alternative than having the application break every time one of these websites change.

The rating system is nice, but I don't think it's sufficient to justify implementing this.

There are other similar websites. The list is currently:

http://consolegrid.com/
http://steam.cryotank.net/
http://www.steamgriddb.com/
http://www.deviantart.com/tag/steamgrid
https://steamgridviewimages.deviantart.com/

I'm closing the issue, but if you think we really should support this website feel free to reopen.

Thank you for your interest!
