### ISSUE TITLE
Smaller grid images in list view and icons in details view

### ISSUE THREAD

**Issue by matthewlsawyer** [boppreh/steamgrid#44]
Are the smaller grid images in the list view and icons in the details view customizable like the full size grid images? It would be great to be able to override/search for these as well. I am willing to tackle this in a fork as I have a bit of Go experience, but I don't know how Steam does things. Any knowledge share would be awesome.

**Comment by boppreh** [comment]
HI @matthewlsawyer 

As far as I know you can change the icon for non-Steam games, which defaults to the icon of the .exe file. These custom icons are stored in `Steam/userdata/{userid}/config/shortcuts.vdf`.

I don't think it's worth implementing this feature for several reasons:

- Works only in non-Steam games.
- Dealing with icons will require searching for a new source of images, and dealing with a new file format (many are in `.ico`).
- Editing `.vdf` files is a pain as the format is proprietary and not documented. It could work well for a time then break everything the next day.
- Icons are much less prominent than grid images, which makes customizing them less useful.

Thanks for the suggestion, but I'm sorry. I would, however, gladly accept a pull request that adds this feature.
