### ISSUE TITLE
Not any issue persay, but is it possible to make it only use local images?

### ISSUE THREAD

**Issue by klepp0906** [boppreh/steamgrid#62]
So in general, I love the program.   Thank you for taking the time <3

I have one small inquiry/request, perhaps its already possible with a CLA...

I prefer to use local images.   Obviously this is possible if you simply place them in the games folder, however if you have one named incorrectly, or are missing one - id prefer it to add nothing at all as opposed to scraping for one.   I'm pretty particular:P

Also a couple bonus questions (small ones!)

1) if multiple images are found (say your scraping from the cloud) how does it choose which it applies?

2) ive created a shortcut, and appended my steamgriddb api, but ive noticed an igdb api option.  is this an "either/or" situation, or can you use both?  If so, how is priority given.  (probably ties into former question)

3) steamgrid.exe wont create/populate a grid directory unless its ran as administrator.  Is this normal behavior? 

4) what is the originals directory created?  even on a blank scrape/run it seems to create and populate that directory as well.

**Comment by Lucki** [comment]
> id prefer it to add nothing at all as opposed to scraping for one.

`--skipsteam --skipgoogle` without an API-Key downloads nothing.

> 1\. if multiple images are found (say your scraping from the cloud) how does it choose which it applies?

No multiple images will be found. It stops at the *first match* with the following priority list:

1. Manual placed images if they differ from the backup
1. Backup
1. `games/` folder
2. Steam servers
3. SteamGridDB (top voted)
    1. Search by appid
    2. Search by name
4. IGDB (Cover only)
5. Google (Banner only)

> 2\. is this an "either/or" situation, or can you use both?

Both.

> 3\. steamgrid.exe wont create/populate a grid directory unless its ran as administrator.  Is this normal behavior?

Can't say, I don't use windows.

> 4\. what is the originals directory created?  even on a blank scrape/run it seems to create and populate that directory as well.

Clean images without an applied overlay. Also used as backup, see above.

**Comment by klepp0906** [comment]
excellent information.  I appreciate your having taken the time :)
