### ISSUE TITLE
Suggestion: Download only nonexistant/old-format covers

### ISSUE THREAD

**Issue by Jacksaur** [boppreh/steamgrid#68]
I mainly use this software to grab cover images for games that don't have any assigned or to fix any that are still using the old cover format. Is there a way to configure the program to only download cover art for games that fit those two cases?
With the new library format, Valve encourage developers to update their cover image alongside ingame events and updates (Hades and Warframe do this, for instance), but as this program downloads and sets art for all games in the whole library, images are permanently shown in the state they were at the time of running. For large libraries as well, the amount of images stored on disk can add up to quite a size.

**Comment by Jacksaur** [comment]
Thanks for the fast reply. How does it interact with images saved in the Games folder for manual assignment? Will it still apply them even when -onlymissingimages is set and cover art already exists?

**Comment by Lucki** [comment]
[It takes the *first match* with the following priority list:](https://github.com/boppreh/steamgrid/issues/62#issuecomment-571817763)

1. Manual placed images if they differ from the backup
1. Backup
1. `games/` folder
2. Steam servers
3. SteamGridDB (top voted)
    1. Search by appid
    2. Search by name
4. IGDB (Cover only)
5. Google (Banner only)

> Will it still apply them even when `-onlymissingimages` is set and cover art already exists?

Already available local files always take precedence. The switch denies 4 and stops from looking further if there's something found at 4. (see above)
