### ISSUE TITLE
Not finding images from SGDB

### ISSUE THREAD

**Issue by paegan69** [boppreh/steamgrid#73]
been having a recurring issue and I'm not sure what's causing it.
The program scans SGDB and claims to not find images for the games that I know that are there. This especially happens with logos in particular. e.g.
(snippet from logfile - _and that's whole other issue entirely_)
```
Processing I Am The Hero (1970/4154)
Banner found from backup
Cover found from backup
Hero found from backup
Logo not found

4000 images could not be found anywhere:
- I Am The Hero (id 498500, Logo)

```
But since this page exists: [https://www.steamgriddb.com/game/12796](https://www.steamgriddb.com/game/12796) it should get the logo from it.

**Comment by Lucki** [comment]
https://github.com/boppreh/steamgrid/issues/66#issuecomment-587575739

**Comment by paegan69** [comment]
does anyone have a download for the updated exe? I have no idea how to compile go code...
