### ISSUE TITLE
SteamGrid isn't recognizing any non steam game anymore

### ISSUE THREAD

**Issue by ferrazpedro** [boppreh/steamgrid#83]
I was trying to import my games to steam after a Windows reinstalation and noticed that steamgrid isn't recognizing non steam games anymore. Does anyone knows what can be causing this?

**Comment by boppreh** [comment]
Steam changed their shortcut database format. Could you please try the new version with a proposed fix?

**Comment by ferrazpedro** [comment]
It's working properly now! Thanks a lot!
