### ISSUE TITLE
Covers not showing in steam

### ISSUE THREAD

**Issue by LucyLikesYourFace** [boppreh/steamgrid#85]
I am running steamgrid v3.2.1 on Manjaro and whilst it detects my non steam games fine and finds assets for them, these do not show in steam, except for in big picture.
The images are in the grid folder but are not being picked up. Adding custom artwork via steam works, but creates a file with a different name/id (2493935266p.png instead of 4186400503p.png)
I am unsure if this is expected or not

**Comment by su-thomas** [comment]
I am running steamgrid 3.2.1 on macOS Catalina and getting the same issue as @LucyLikesYourFace

**Comment by dhruvinsh** [comment]
Yes that is correct. The issue is, cover is being downloaded but the ID (name) of the cover is different.

For example, Game called DeadCell: cover downloaded by steamgrid is, 3495713025p.png but required name need to be 3469739720p.png

I did manual cover set, and there after it worked fine.

**Comment by Lucki** [comment]
Could you please try v3.2.0? The only change to v3.2.1 had something to do with this.

**Comment by LucyLikesYourFace** [comment]
> Could you please try v3.2.0? The only change to v3.2.1 had something to do with this.

just tried, 3.2.0 does not detect any non steam games at all

**Comment by Lucki** [comment]
I added a commit to #69 that should fix this.

**Comment by LucyLikesYourFace** [comment]
I've tried that out but it doesn't seem to work, the ids its showing isn't matching what steam is using and it didn't change the artwork

**Comment by Lucki** [comment]
Not sure what's wrong here.
The target and name is correctly extracted and the crc32 number is also correct.
The bit operations don't seem to do anything. The resulting name is the crc32 checksum.
So I assume the bit shifting and the OR operations don't work the way they should but I'm not sure why.

A simple example if anyone want to tinker around:
Target: `"corsix-th"`
Name: `CorsixTH`
Target + Name: `"corsix-th"CorsixTH`
CRC32: [`2209561550`](https://crccalc.com/?crc="corsix-th"CorsixTH&method=crc32&datatype=ascii&outtype=dec)

Steam: `2257678613`

https://github.com/SteamGridDB/steamgriddb-manager/blob/e293f97c53468374e15954da9c0ea2f27ca81c07/src/js/Steam.js#L195-L202

**Comment by LucyLikesYourFace** [comment]
I recreated the steps in python and im getting the same result steamgrid is for the id. Did steam itself change something?

**Comment by Lucki** [comment]
> Did steam itself change something?

I think so. All the times I've checked with shortcuts that already existed and for them it still works totally fine. But it fails for newly created shortcuts - even if I set them to the old values. My current guess is that the new binary field is somehow connected.

**Comment by Lucki** [comment]
> I added a commit to #69 that should fix this.

Now for real.

**Comment by LucyLikesYourFace** [comment]
Thank you, that fix works as far as I can tell

**Comment by forenta** [comment]
Could someone compile this to a 3.2.2 release?

**Comment by ScranchNew** [comment]
[steamgrid.zip](https://github.com/boppreh/steamgrid/files/7816267/steamgrid.zip)

I compiled the latest version of this repo for anyone still suffering from this bug
