### ISSUE TITLE
covers show up in big picture but not normal steam

### ISSUE THREAD

**Issue by el1x3r** [boppreh/steamgrid#86]
ever since i added another steam account and removed it knowing it did something, every time i run the software, it applies the covers on big picture (which i rarely ever use), but normal steams covers don't show up?

is there anything i should do to make them show up? i really don't want to have to add all of them manually

**Comment by Lucki** [comment]
Are the cover format images in the grid folder? (`$steampath/userdata/$userid/config/grid/*p.png`)
What's the command you've run?
