### ISSUE TITLE
No logo was downloaded?

### ISSUE THREAD

**Issue by Lojalfan** [boppreh/steamgrid#87]
For example: it downloaded Hero and Cover images for Prince of Persia but not the logo. Actually it didn't download the missing ones for any game. I tried with -styles "official" and the same without quotation marks.

**Comment by Lojalfan** [comment]
None of the other fixes work for me. I've tried:

* Recompiling from the source code
* changing line 149 in download.go to only "filter := steamGridFilter"

**Comment by Lucki** [comment]
Duplicate of #85

**Comment by Lucki** [comment]
Steamgrid does not have a style named "official".
