### ISSUE TITLE
When extracted, files in /steamgrid/ delete themselves immediately.

### ISSUE THREAD

**Issue by Tantusar** [boppreh/steamgrid#9]
As above.

**Comment by boppreh** [comment]
They disappear as soon as you extract, without running the program? If that's the case, it can't possibly be steamgrid and has to be some other running program.

The most likely reason is an anti-virus miss-classifying it and putting the files in quarantine. Steamgrid is an executable file, written in an uncommon language (Go); I can see how an eager anti virus may find it suspicious. So please check your quarantine.

If that's not the case, I would love to have more details to debug this strange problem. What OS and security software are you using?

**Comment by Tantusar** [comment]
Windows 7 Starter SP1
Up-to-date Avast Free Antivirus
Up-to-date Zonealarm Free Firewall

Possibly Avast, hadn't thought of that.

**Comment by Tantusar** [comment]
Oh yeah, it's Avast.

(Stupid Avast, where's my chest?)

**Comment by boppreh** [comment]
I'm going to close this ticket now. I don't think this program is important enough to warrant registering with anti-virus companies or trying to work around them.

If there's anything simpler, or you find it was Steamgrid's fault, I'm all ears.

Thank you
