### ISSUE TITLE
Client grabs the wrong game IDs

### ISSUE THREAD

**Issue by forenta** [boppreh/steamgrid#91]
Basically, the tool does exactly what it is supposed to do for me - retrieving missing images from the SteamGrid database works as it should and also the additions from the Games folder are retrieved correctly. According to the log file, everything works as it should.

Unfortunately, the tool assigns a 19-20 digit ID to the games instead of the 10 digit IDs that Steam actually assigns to the games for me. For example, I recently added 'The First Tree' - the tool assigns them as 
C:\Program Files (x86)\Steam\userdata\[number]\config\grid\17784185938872631296.jpg
although it should be
C:\Program Files (x86)\Steam\userdata\[number]\config\grid\3176493060.jpg

It seems that the issue occurs with every game. I'll fix the IDs by editing the entry in the Steam client and see which file in C:\Program Files (x86)\Steam\userdata\[numer]\config\librarycache has been changed recently, that's the correct 10 digit ID.

Anyone has an idea what I'm doing wrong?

**Comment by Lucki** [comment]
I guess this is a duplicate of #85 , it's already fixed but no release yet.

**Comment by forenta** [comment]
Thanks for this! I had searched for a corresponding thread, did not suspect the issue behind this tittle. In this respect, it is indeed a duplicate of this ticket.
