### ISSUE TITLE
Setting custom background and logos for Non-Grid-View

### ISSUE THREAD

**Issue by hashworks** [boppreh/steamgrid#98]
Steam allows to set custom backgrounds and logos:
![example](https://fb.hash.works/g79XZdgi/)

Do you have any idea if those can be set automatically? It would be a great addition to steamgrid.

**Comment by Lucki** [comment]
Already fixed by #57

**Comment by hashworks** [comment]
Hm, this doesn't seem to work for any of my non-steam games. For example, according to the log a banner was found for "Resident Evil Village":
```
$ ./steamgrid -nonsteamonly -steamgriddb "foo"
[...]
Processing Resident Evil Village (20/22)
Banner found from SteamGridDB
Cover found from SteamGridDB
Hero found from SteamGridDB
Logo not found
[...]
36 images downloaded and 0 overlays applied.

36 images were found on SteamGridDB and may not be in full quality or accurate:
[...]
* DOOM Eternal (steam id 3201084755, Banner)
[...]
```

![banner-example](https://fb.hash.works/j5wlY/)

![doom-files](https://fb.hash.works/ttmIG/)

![doom-grid](https://fb.hash.works/lRqQP/)

I'm using the latest v3.2.1 on Linux. Any idea?

**Comment by Lucki** [comment]
> I'm using the latest v3.2.1 on Linux. Any idea?

The latest release is missing #69 specifically d7f07bc.

**Comment by hashworks** [comment]
Aaaah, the MR was merged on 2021-03, but the latest release is from 2020-12. Got it. @boppreh, maybe a new release would be good?
